name: deploy 🚀

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install and build
      run: |
        npm install
        npm run build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_BLOG_DEPLOY_KEY }}
        external_repository: ddalpange/ddalpange.github.io
        publish_branch: master  # default: gh-pages
        publish_dir: ./out
    